[package]
name = "unwrap_display"
version = "0.0.0"
edition = "2021"
authors = ["Robert Hildebrandt"]

license = "Apache-2.0"
repository = "https://github.com/Robert42/unwrap_display"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
